if not exists (select object_id from sys.objects where type = 'P' and name = 'spConsensusLearningSessionXrefModify')
  exec ('create procedure dbo.spConsensusLearningSessionXrefModify as select 1 as temp')
go
alter procedure dbo.spConsensusLearningSessionXrefModify(@PA_SXREF_ID varchar(11) = null output, @PA_SXREF_LOCK varchar(11) = null output, @PA_SXREF_COURSE_ID varchar(11) = null output, @PA_SXREF_ACT_ID varchar(11) = null output, @PA_SXREF_REAL tinyint = null output, @PA_SXREF_ELEMENT tinyint = null output, @PA_SXREF_MANDATORY tinyint = null output, @PA_SXREF_INV_PRINT tinyint = null output, @PA_SXREF_CURRENCY varchar(3) = null output, @PA_SXREF_PRICE decimal(19, 4) = null output, @PA_SXREF_BLOCK_PRICE decimal(19, 4) = null output, @PA_SXREF_PRICE_BC decimal(19, 4) = null output, @PA_SXREF_BLK_PRICE_BC decimal(19, 4) = null output, @PA_SXREF_VATCD varchar(25) = null output, @PA_SXREF_REV_CODE varchar(40) = null output, @PA_SXREF_COST_CODE varchar(40) = null output, @PA_SXREF_DO_NOT_INV tinyint = null output, @PA_SXREF_SHOW_SALES tinyint = null output, @PA_SXREF_NO_IN_SET integer = null output, @PA_SXREF_RETAIL_PRICE decimal(19, 4) = null output, @PA_SXREF_COST_PRICE decimal(19, 4) = null output, @PA_SXREF_RET_PRICE_BC decimal(19, 4) = null output, @PA_SXREF_CST_PRICE_BC decimal(19, 4) = null output, @PA_SXREF_RET_PRIC_BC2 decimal(19, 4) = null output, @PA_SXREF_CST_PRIC_BC2 decimal(19, 4) = null output, @PA_SXREF_PRICE_A decimal(19, 4) = null output, @PA_SXREF_PRICE_B decimal(19, 4) = null output, @PA_SXREF_PRICE_C decimal(19, 4) = null output, @PA_SXREF_PRICE_D decimal(19, 4) = null output, @PA_SXREF_PRICE_E decimal(19, 4) = null output, @PA_SXREF_DEFAULT tinyint = null output, @PA_SXREF_PL_ID varchar(11) = null output, @PA_SXREF_TICKET tinyint = null output, @PA_SXREF_GROUP_QTY tinyint = null output, @PA_SXREF_GROUP_DTE tinyint = null output, @PA_SXREF_GROUP_QTY_ID varchar(11) = null output, @PA_SXREF_GROUP_DTE_ID varchar(11) = null output, @PA_SXREF_QTY_MIN integer = null output, @PA_SXREF_QTY_MAX integer = null output, @PA_SXREF_VALID_FROM datetime = null output, @PA_SXREF_VALID_UNTIL datetime = null output, @PA_SXREF_BEFORE_DAYS integer = null output, @PA_SXREF_CHARGEABLE integer = null output, @PA_SXREF_MAIN_SESSION tinyint = null output, @PA_SXREF_ETT_ID varchar(11) = null output, @PA_SXREF_GRP_SG_ID varchar(11) = null output, @PA_SXREF_STRM_SG_ID varchar(11) = null output, @PA_SXREF_GRID_START varchar(20) = null output, @PA_SXREF_GRID_END varchar(20) = null output, @PA_SXREF_SESS_PNTS integer = null output, @PA_SXREF_MAST_SESS integer = null output, @PA_SXREF_SELECTED tinyint = null output, @PA_SXREF_COUNT_DEL tinyint = null output, @PA_SXREF_PAY_PNTS tinyint = null output, @PA_SXREF_CODE varchar(11) = null output, @PA_SXREF_ACTXREF_ID varchar(11) = null output, @PA_SXREF_PROD_ID varchar(11) = null output, @PA_SXREF_PL_NAME varchar(30) = null output, @PA_SXREF_PRS_ID varchar(11) = null output, @PA_SXREF_MEMBER tinyint = null output, @PA_SXREF_START_DAY integer = null output, @PA_SXREF_END_DAY integer = null output, @PA_SXREF_LST_PRICE decimal(19, 4) = null output, @PA_SXREF_STUDENT tinyint = null output, @PA_SXREF_BOM_ID varchar(11) = null output, @PA_SXREF_EP_ID integer = null output, @PA_SXREF_VALID_DATE tinyint = null output, @PA_SXREF_REGION varchar(40) = null output, @PA_SXREF_CSG_ID integer = null output, @_AUDIT_USER_ID varchar(3) = null) as 
begin
  update dbo.Session_Xref set
    SXREF_MOD_DATE = getDate(),
    SXREF_MOD_BY = @_AUDIT_USER_ID,
    SXREF_LOCK = @PA_SXREF_LOCK,
    SXREF_COURSE_ID = @PA_SXREF_COURSE_ID,
    SXREF_ACT_ID = @PA_SXREF_ACT_ID,
    SXREF_REAL = @PA_SXREF_REAL,
    SXREF_ELEMENT = @PA_SXREF_ELEMENT,
    SXREF_MANDATORY = @PA_SXREF_MANDATORY,
    SXREF_INV_PRINT = @PA_SXREF_INV_PRINT,
    SXREF_CURRENCY = @PA_SXREF_CURRENCY,
    SXREF_PRICE = @PA_SXREF_PRICE,
    SXREF_BLOCK_PRICE = @PA_SXREF_BLOCK_PRICE,
    SXREF_PRICE_BC = @PA_SXREF_PRICE_BC,
    SXREF_BLK_PRICE_BC = @PA_SXREF_BLK_PRICE_BC,
    SXREF_VATCD = @PA_SXREF_VATCD,
    SXREF_REV_CODE = @PA_SXREF_REV_CODE,
    SXREF_COST_CODE = @PA_SXREF_COST_CODE,
    SXREF_DO_NOT_INV = @PA_SXREF_DO_NOT_INV,
    SXREF_SHOW_SALES = @PA_SXREF_SHOW_SALES,
    SXREF_NO_IN_SET = @PA_SXREF_NO_IN_SET,
    SXREF_RETAIL_PRICE = @PA_SXREF_RETAIL_PRICE,
    SXREF_COST_PRICE = @PA_SXREF_COST_PRICE,
    SXREF_RET_PRICE_BC = @PA_SXREF_RET_PRICE_BC,
    SXREF_CST_PRICE_BC = @PA_SXREF_CST_PRICE_BC,
    SXREF_RET_PRIC_BC2 = @PA_SXREF_RET_PRIC_BC2,
    SXREF_CST_PRIC_BC2 = @PA_SXREF_CST_PRIC_BC2,
    SXREF_PRICE_A = @PA_SXREF_PRICE_A,
    SXREF_PRICE_B = @PA_SXREF_PRICE_B,
    SXREF_PRICE_C = @PA_SXREF_PRICE_C,
    SXREF_PRICE_D = @PA_SXREF_PRICE_D,
    SXREF_PRICE_E = @PA_SXREF_PRICE_E,
    SXREF_DEFAULT = @PA_SXREF_DEFAULT,
    SXREF_PL_ID = @PA_SXREF_PL_ID,
    SXREF_TICKET = @PA_SXREF_TICKET,
    SXREF_GROUP_QTY = @PA_SXREF_GROUP_QTY,
    SXREF_GROUP_DTE = @PA_SXREF_GROUP_DTE,
    SXREF_GROUP_QTY_ID = @PA_SXREF_GROUP_QTY_ID,
    SXREF_GROUP_DTE_ID = @PA_SXREF_GROUP_DTE_ID,
    SXREF_QTY_MIN = @PA_SXREF_QTY_MIN,
    SXREF_QTY_MAX = @PA_SXREF_QTY_MAX,
    SXREF_VALID_FROM = @PA_SXREF_VALID_FROM,
    SXREF_VALID_UNTIL = @PA_SXREF_VALID_UNTIL,
    SXREF_BEFORE_DAYS = @PA_SXREF_BEFORE_DAYS,
    SXREF_CHARGEABLE = @PA_SXREF_CHARGEABLE,
    SXREF_MAIN_SESSION = @PA_SXREF_MAIN_SESSION,
    SXREF_ETT_ID = @PA_SXREF_ETT_ID,
    SXREF_GRP_SG_ID = @PA_SXREF_GRP_SG_ID,
    SXREF_STRM_SG_ID = @PA_SXREF_STRM_SG_ID,
    SXREF_GRID_START = @PA_SXREF_GRID_START,
    SXREF_GRID_END = @PA_SXREF_GRID_END,
    SXREF_SESS_PNTS = @PA_SXREF_SESS_PNTS,
    SXREF_MAST_SESS = @PA_SXREF_MAST_SESS,
    SXREF_SELECTED = @PA_SXREF_SELECTED,
    SXREF_COUNT_DEL = @PA_SXREF_COUNT_DEL,
    SXREF_PAY_PNTS = @PA_SXREF_PAY_PNTS,
    SXREF_CODE = @PA_SXREF_CODE,
    SXREF_ACTXREF_ID = @PA_SXREF_ACTXREF_ID,
    SXREF_PROD_ID = @PA_SXREF_PROD_ID,
    SXREF_PL_NAME = @PA_SXREF_PL_NAME,
    SXREF_PRS_ID = @PA_SXREF_PRS_ID,
    SXREF_MEMBER = @PA_SXREF_MEMBER,
    SXREF_START_DAY = @PA_SXREF_START_DAY,
    SXREF_END_DAY = @PA_SXREF_END_DAY,
    SXREF_LST_PRICE = @PA_SXREF_LST_PRICE,
    SXREF_STUDENT = @PA_SXREF_STUDENT,
    SXREF_BOM_ID = @PA_SXREF_BOM_ID,
    SXREF_EP_ID = @PA_SXREF_EP_ID,
    SXREF_VALID_DATE = @PA_SXREF_VALID_DATE,
    SXREF_REGION = @PA_SXREF_REGION,
    SXREF_CSG_ID = @PA_SXREF_CSG_ID
  where SXREF_ID = @PA_SXREF_ID;
end
go
