if not exists (select object_id from sys.objects where type = 'P' and name = 'spConsensusContactTrainerModify')
  exec ('create procedure dbo.spConsensusContactTrainerModify as select 1 as temp')
go
alter procedure dbo.spConsensusContactTrainerModify(@PA_TRAIN_ID varchar(11) = null output, @PA_TRAIN_LOCK varchar(11) = null output, @PA_TRAIN_ADD_DATE datetime = null output, @PA_TRAIN_ADD_BY varchar(20) = null output, @PA_TRAIN_MOD_DATE datetime = null output, @PA_TRAIN_MOD_BY varchar(20) = null output, @PA_TRAIN_RCV_DATE datetime = null output, @PA_TRAIN_RCV_FROM varchar(11) = null output, @PA_TRAIN_PROLE_ID varchar(11) = null output, @PA_TRAIN_APP_ID varchar(11) = null output, @PA_TRAIN_START_DATE datetime = null output, @PA_TRAIN_STATUS varchar(25) = null output, @PA_TRAIN_REVIEW_DATE datetime = null output, @PA_TRAIN_REF varchar(25) = null output, @PA_TRAIN_COST decimal(12, 2) = null output, @PA_TRAIN_USERCHAR_1 varchar(100) = null output, @PA_TRAIN_USERCHAR_2 varchar(100) = null output, @PA_TRAIN_USERCHAR_3 varchar(100) = null output, @PA_TRAIN_USERCHAR_4 varchar(100) = null output, @PA_TRAIN_USERCHAR_5 varchar(100) = null output, @PA_TRAIN_USERCHAR_6 varchar(100) = null output, @PA_TRAIN_USERINT_1 tinyint = null output, @PA_TRAIN_USERINT_2 tinyint = null output, @PA_TRAIN_USERINT_3 tinyint = null output, @PA_TRAIN_USERINT_4 tinyint = null output, @PA_TRAIN_USERINT_5 tinyint = null output, @PA_TRAIN_USERINT_6 tinyint = null output, @PA_TRAIN_USERNUM_1 decimal(16, 2) = null output, @PA_TRAIN_USERNUM_2 decimal(16, 2) = null output, @PA_TRAIN_USERNUM_3 decimal(16, 2) = null output, @PA_TRAIN_USERNUM_4 decimal(16, 2) = null output, @PA_TRAIN_USERNUM_5 decimal(16, 2) = null output, @PA_TRAIN_USERNUM_6 decimal(16, 2) = null output, @PA_TRAIN_USERDATE_1 datetime = null output, @PA_TRAIN_USERDATE_2 datetime = null output, @PA_TRAIN_USERDATE_3 datetime = null output, @PA_TRAIN_USERDATE_4 datetime = null output, @PA_TRAIN_USERDATE_5 datetime = null output, @PA_TRAIN_USERDATE_6 datetime = null output, @PA_TRAIN_BIOG varchar(max) = null output, @PA_TRAIN_ATTRIB01 varchar(40) = null output, @PA_TRAIN_DAY_COST decimal(19, 2) = null output, @PA_TRAIN_HOUR_COST decimal(19, 2) = null output, @PA_TRAIN_BASE_POSTCODE varchar(12) = null output, @PA_TRAIN_BASE_LAT decimal(19, 4) = null output, @PA_TRAIN_BASE_LONG decimal(19, 4) = null output, @PA_TRAIN_SELCO_SP_ID varchar(11) = null output, @PA_TRAIN_INS_EXPIRY datetime = null output, @PA_TRN_UNIQUE_REF varchar(50) = null output, @PA_TRAIN_FEE_NOTES_TEXT_ID varchar(11) = null output, @PA_TRAIN_HOTEL_REQ_TEXT_ID varchar(11) = null output, @PA_TRAIN_OTHER_INFO_TEXT_ID varchar(11) = null output, @PA_TRAIN_PASSWORD varchar(255) = null output, @PA_TRAIN_WEB tinyint = null output, @PA_TRAIN_BIOG_PIC_URL varchar(2000) = null output, @PA_TRAIN_SY_TYPE integer = null output, @_AUDIT_USER_ID varchar(3) = null) as 
begin
  update dbo.Trainer set
    TRAIN_LOCK = @PA_TRAIN_LOCK,
    TRAIN_ADD_DATE = @PA_TRAIN_ADD_DATE,
    TRAIN_ADD_BY = @PA_TRAIN_ADD_BY,
    TRAIN_MOD_DATE = @PA_TRAIN_MOD_DATE,
    TRAIN_MOD_BY = @PA_TRAIN_MOD_BY,
    TRAIN_RCV_DATE = @PA_TRAIN_RCV_DATE,
    TRAIN_RCV_FROM = @PA_TRAIN_RCV_FROM,
    TRAIN_PROLE_ID = @PA_TRAIN_PROLE_ID,
    TRAIN_APP_ID = @PA_TRAIN_APP_ID,
    TRAIN_START_DATE = @PA_TRAIN_START_DATE,
    TRAIN_STATUS = @PA_TRAIN_STATUS,
    TRAIN_REVIEW_DATE = @PA_TRAIN_REVIEW_DATE,
    TRAIN_REF = @PA_TRAIN_REF,
    TRAIN_COST = @PA_TRAIN_COST,
    TRAIN_USERCHAR_1 = @PA_TRAIN_USERCHAR_1,
    TRAIN_USERCHAR_2 = @PA_TRAIN_USERCHAR_2,
    TRAIN_USERCHAR_3 = @PA_TRAIN_USERCHAR_3,
    TRAIN_USERCHAR_4 = @PA_TRAIN_USERCHAR_4,
    TRAIN_USERCHAR_5 = @PA_TRAIN_USERCHAR_5,
    TRAIN_USERCHAR_6 = @PA_TRAIN_USERCHAR_6,
    TRAIN_USERINT_1 = @PA_TRAIN_USERINT_1,
    TRAIN_USERINT_2 = @PA_TRAIN_USERINT_2,
    TRAIN_USERINT_3 = @PA_TRAIN_USERINT_3,
    TRAIN_USERINT_4 = @PA_TRAIN_USERINT_4,
    TRAIN_USERINT_5 = @PA_TRAIN_USERINT_5,
    TRAIN_USERINT_6 = @PA_TRAIN_USERINT_6,
    TRAIN_USERNUM_1 = @PA_TRAIN_USERNUM_1,
    TRAIN_USERNUM_2 = @PA_TRAIN_USERNUM_2,
    TRAIN_USERNUM_3 = @PA_TRAIN_USERNUM_3,
    TRAIN_USERNUM_4 = @PA_TRAIN_USERNUM_4,
    TRAIN_USERNUM_5 = @PA_TRAIN_USERNUM_5,
    TRAIN_USERNUM_6 = @PA_TRAIN_USERNUM_6,
    TRAIN_USERDATE_1 = @PA_TRAIN_USERDATE_1,
    TRAIN_USERDATE_2 = @PA_TRAIN_USERDATE_2,
    TRAIN_USERDATE_3 = @PA_TRAIN_USERDATE_3,
    TRAIN_USERDATE_4 = @PA_TRAIN_USERDATE_4,
    TRAIN_USERDATE_5 = @PA_TRAIN_USERDATE_5,
    TRAIN_USERDATE_6 = @PA_TRAIN_USERDATE_6,
    TRAIN_BIOG = @PA_TRAIN_BIOG,
    TRAIN_ATTRIB01 = @PA_TRAIN_ATTRIB01,
    TRAIN_DAY_COST = @PA_TRAIN_DAY_COST,
    TRAIN_HOUR_COST = @PA_TRAIN_HOUR_COST,
    TRAIN_BASE_POSTCODE = @PA_TRAIN_BASE_POSTCODE,
    TRAIN_BASE_LAT = @PA_TRAIN_BASE_LAT,
    TRAIN_BASE_LONG = @PA_TRAIN_BASE_LONG,
    TRAIN_SELCO_SP_ID = @PA_TRAIN_SELCO_SP_ID,
    TRAIN_INS_EXPIRY = @PA_TRAIN_INS_EXPIRY,
    TRN_UNIQUE_REF = @PA_TRN_UNIQUE_REF,
    TRAIN_FEE_NOTES_TEXT_ID = @PA_TRAIN_FEE_NOTES_TEXT_ID,
    TRAIN_HOTEL_REQ_TEXT_ID = @PA_TRAIN_HOTEL_REQ_TEXT_ID,
    TRAIN_OTHER_INFO_TEXT_ID = @PA_TRAIN_OTHER_INFO_TEXT_ID,
    TRAIN_PASSWORD = @PA_TRAIN_PASSWORD,
    TRAIN_WEB = @PA_TRAIN_WEB,
    TRAIN_BIOG_PIC_URL = @PA_TRAIN_BIOG_PIC_URL,
    TRAIN_SY_TYPE = @PA_TRAIN_SY_TYPE
  where TRAIN_ID = @PA_TRAIN_ID;
end
go
