if not exists (select object_id from sys.objects where name = 'vConsensusBookingLines' and type = 'v')
  exec ('create view dbo.vConsensusBookingLines as select 1 as temp')
go

alter view dbo.vConsensusBookingLines as 
	select	ELEM_ID
			,ISNULL(PROLE_PN_NAME,'TBA') as [PROLE_PN_NAME]
			,ELEM_TYPE_DESC
			,ELEM_DESCRIPTION	
			,ELEM_STATUS_DESC
			,ELEM_QTY
			,ELEM_UNT_PRICE
			,ELEM_PRICE
			,ELEM_VAT_AMT
			,ISNULL(ELEM_START_DATE,ELEM_ADD_DATE) as ELEM_START_DATE
			,ISNULL(ELEM_END_DATE,ELEM_ADD_DATE) as ELEM_END_DATE
			,ELEM_INVOICED
			,ELEM_MAIN_SESSION
			,uri = 'learning/bookingline/' + convert(varchar, ELEM_ID)
			,ELEM_BOOK_ID
			,ELEM_DEL_ID
			,ELEM_GRP_ID
			,ISNULL(PN_SURNAME,'TBA') as PN_SURNAME
			,ELEM_CANCELLED
			,ELEM_SHOW_SALES
			,COALESCE(PROLE_ID,BOOK_PROLE_ID) as PROLE_ID
	FROM ELEMENT
		INNER JOIN DELEGATE ON DEL_ID = ELEM_DEL_ID
		LEFT JOIN BOOKING ON BOOK_ID = ELEM_BOOK_ID
		LEFT JOIN PRODUCT ON PROD_ID = ELEM_PROD_ID
		LEFT JOIN PERSON_ROLE ON PROLE_ID = DEL_PROLE_ID
		LEFT JOIN PERSON ON PN_ID = PROLE_PERSON_ID
		LEFT JOIN vELEM_STATUS ON vELEM_STATUS.ELEM_STATUS = ELEMENT.ELEM_STATUS
		LEFT JOIN vELEM_TYPE ON vELEM_TYPE.ELEM_TYPE = ELEMENT.ELEM_TYPE
go