//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consensus.Web.BackOffice.learning.controls {
    
    
    public partial class EventProductDetail {
        
        /// <summary>
        /// EventProductSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.Controls.TabPage EventProductSection;
        
        /// <summary>
        /// EventId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.Controls.HiddenField EventId;
        
        /// <summary>
        /// EventProductDetailSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.learning.controls.EventProductDetailSection EventProductDetailSection;
        
        /// <summary>
        /// PriceSection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.Controls.TabPage PriceSection;
        
        /// <summary>
        /// EventProductPriceDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.learning.controls.SessionPriceList EventProductPriceDetails;
    }
}
