//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consensus.Web.BackOffice.document {
    
    
    public partial class PackPage {
        
        /// <summary>
        /// PackDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.document.controls.PackDetails PackDetails;
        
        /// <summary>
        /// PackEmailDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.document.controls.PackEmailDetail PackEmailDetail;
        
        /// <summary>
        /// BottomTabControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.Controls.TabControl BottomTabControl;
        
        /// <summary>
        /// DocumentTemplateList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.document.controls.DocumentTemplateList DocumentTemplateList;
    }
}
