if not exists (select object_id from sys.objects where type = 'P' and name = 'spConsensusMarketingCampaignModify')
  exec ('create procedure dbo.spConsensusMarketingCampaignModify as select 1 as temp')
go
alter procedure dbo.spConsensusMarketingCampaignModify(@PA_CMP_ID varchar(11) = null output, @PA_CMP_NAME varchar(30) = null output, @PA_CMP_START_DATE datetime = null output, @PA_CMP_END_DATE datetime = null output, @PA_CMP_REGION varchar(20) = null output, @PA_CMP_OBJ_TEXT_ID varchar(11) = null output, @PA_CMP_SEL_TEXT_ID varchar(11) = null output, @PA_CMP_RVW_TEXT_ID varchar(11) = null output, @PA_CMP_BUDGET_COSTS float = null output, @PA_CMP_ACTUAL_COSTS float = null output, @PA_CMP_REPLIES float = null output, @PA_CMP_ORDERS float = null output, @PA_CMP_ORDER_VALUE float = null output, @PA_CMP_UPDATED datetime = null output, @PA_CMP_MOD_BY_SYS varchar(20) = null output, @PA_CMP_LOCK varchar(10) = null output, @PA_CMP_BUDGET_COST_BC float = null output, @PA_CMP_ACTUAL_COST_BC float = null output, @PA_CMP_ORDER_VALUE_BC float = null output, @PA_CMP_CURRENCY_TYPE varchar(3) = null output, @PA_CMP_MAILINGS integer = null output, @PA_CMP_TELESALES integer = null output, @PA_CMP_BOOKINGS integer = null output, @PA_CMP_BOOK_VALUE float = null output, @PA_CMP_QUOTES integer = null output, @PA_CMP_QUO_VALUE float = null output, @PA_CMP_SALES integer = null output, @PA_CMP_SALE_VALUE float = null output, @PA_CMP_CALC_ACT float = null output, @PA_CMP_CALC_EST float = null output, @PA_CMP_OPP_TOT integer = null output, @PA_CMP_PROJ_ID varchar(11) = null output, @PA_CMP_BUDGET_COST_BC2 decimal(19, 2) = null output, @PA_CMP_ACTUAL_COST_BC2 decimal(19, 2) = null output, @PA_CMP_ORDER_VALUE_BC2 decimal(19, 2) = null output, @PA_CMP_SELCO_SP_ID varchar(11) = null output, @PA_CMP_TARGET_OPP integer = null output, @PA_CMP_TARGET_REPLIES integer = null output, @PA_CMP_TARGET_OPP_VAL float = null output, @PA_CMP_TARGET_BOOK_VAL float = null output, @PA_CMP_PROLE_ID varchar(11) = null output, @PA_CMP_APP_PROLE_ID varchar(11) = null output, @PA_CMP_EMAILS_SENT integer = null output, @PA_CMP_EMAILS_OPENED integer = null output, @PA_CMP_LINKS_CLICKED integer = null output, @PA_CMP_LZ_CLICKED integer = null output, @PA_CMP_SURVEYS_COMPLETED integer = null output, @PA_CMP_GLOBAL_UNSUBSCRIBES integer = null output, @PA_CMP_LIST_UNSUBSCRIBES integer = null output, @PA_CMP_DOCS_DOWNLOADS integer = null output, @PA_CMP_BOUNCE_BACKS integer = null output, @PA_CMP_EMAILS_SENT_TARGET integer = null output, @PA_CMP_EMAILS_OPENED_TARGET integer = null output, @PA_CMP_LINKS_CLICKED_TARGET integer = null output, @PA_CMP_LZ_CLICKED_TARGET integer = null output, @PA_CMP_SURVEYS_COMPLETED_TARGET integer = null output, @PA_CMP_GLOBAL_UNSUBSCRIBES_TARGET integer = null output, @PA_CMP_LIST_UNSUBSCRIBES_TARGET integer = null output, @PA_CMP_DOCS_DOWNLOADS_TARGET integer = null output, @PA_CMP_BOUNCE_BACKS_TARGET integer = null output, @PA_CMP_QCODE varchar(15) = null output, @PA_CMP_CURRENT tinyint = null output, @_AUDIT_USER_ID varchar(3) = null) as 
begin
  update dbo.Campaign set
    CMP_MOD_DATE = getDate(),
    CMP_MOD_BY = @_AUDIT_USER_ID,
    CMP_NAME = @PA_CMP_NAME,
    CMP_START_DATE = @PA_CMP_START_DATE,
    CMP_END_DATE = @PA_CMP_END_DATE,
    CMP_REGION = @PA_CMP_REGION,
    CMP_OBJ_TEXT_ID = @PA_CMP_OBJ_TEXT_ID,
    CMP_SEL_TEXT_ID = @PA_CMP_SEL_TEXT_ID,
    CMP_RVW_TEXT_ID = @PA_CMP_RVW_TEXT_ID,
    CMP_BUDGET_COSTS = @PA_CMP_BUDGET_COSTS,
    CMP_ACTUAL_COSTS = @PA_CMP_ACTUAL_COSTS,
    CMP_REPLIES = @PA_CMP_REPLIES,
    CMP_ORDERS = @PA_CMP_ORDERS,
    CMP_ORDER_VALUE = @PA_CMP_ORDER_VALUE,
    CMP_UPDATED = @PA_CMP_UPDATED,
    CMP_MOD_BY_SYS = @PA_CMP_MOD_BY_SYS,
    CMP_LOCK = @PA_CMP_LOCK,
    CMP_BUDGET_COST_BC = @PA_CMP_BUDGET_COST_BC,
    CMP_ACTUAL_COST_BC = @PA_CMP_ACTUAL_COST_BC,
    CMP_ORDER_VALUE_BC = @PA_CMP_ORDER_VALUE_BC,
    CMP_CURRENCY_TYPE = @PA_CMP_CURRENCY_TYPE,
    CMP_MAILINGS = @PA_CMP_MAILINGS,
    CMP_TELESALES = @PA_CMP_TELESALES,
    CMP_BOOKINGS = @PA_CMP_BOOKINGS,
    CMP_BOOK_VALUE = @PA_CMP_BOOK_VALUE,
    CMP_QUOTES = @PA_CMP_QUOTES,
    CMP_QUO_VALUE = @PA_CMP_QUO_VALUE,
    CMP_SALES = @PA_CMP_SALES,
    CMP_SALE_VALUE = @PA_CMP_SALE_VALUE,
    CMP_CALC_ACT = @PA_CMP_CALC_ACT,
    CMP_CALC_EST = @PA_CMP_CALC_EST,
    CMP_OPP_TOT = @PA_CMP_OPP_TOT,
    CMP_PROJ_ID = @PA_CMP_PROJ_ID,
    CMP_BUDGET_COST_BC2 = @PA_CMP_BUDGET_COST_BC2,
    CMP_ACTUAL_COST_BC2 = @PA_CMP_ACTUAL_COST_BC2,
    CMP_ORDER_VALUE_BC2 = @PA_CMP_ORDER_VALUE_BC2,
    CMP_SELCO_SP_ID = @PA_CMP_SELCO_SP_ID,
    CMP_TARGET_OPP = @PA_CMP_TARGET_OPP,
    CMP_TARGET_REPLIES = @PA_CMP_TARGET_REPLIES,
    CMP_TARGET_OPP_VAL = @PA_CMP_TARGET_OPP_VAL,
    CMP_TARGET_BOOK_VAL = @PA_CMP_TARGET_BOOK_VAL,
    CMP_PROLE_ID = @PA_CMP_PROLE_ID,
    CMP_APP_PROLE_ID = @PA_CMP_APP_PROLE_ID,
    CMP_EMAILS_SENT = @PA_CMP_EMAILS_SENT,
    CMP_EMAILS_OPENED = @PA_CMP_EMAILS_OPENED,
    CMP_LINKS_CLICKED = @PA_CMP_LINKS_CLICKED,
    CMP_LZ_CLICKED = @PA_CMP_LZ_CLICKED,
    CMP_SURVEYS_COMPLETED = @PA_CMP_SURVEYS_COMPLETED,
    CMP_GLOBAL_UNSUBSCRIBES = @PA_CMP_GLOBAL_UNSUBSCRIBES,
    CMP_LIST_UNSUBSCRIBES = @PA_CMP_LIST_UNSUBSCRIBES,
    CMP_DOCS_DOWNLOADS = @PA_CMP_DOCS_DOWNLOADS,
    CMP_BOUNCE_BACKS = @PA_CMP_BOUNCE_BACKS,
    CMP_EMAILS_SENT_TARGET = @PA_CMP_EMAILS_SENT_TARGET,
    CMP_EMAILS_OPENED_TARGET = @PA_CMP_EMAILS_OPENED_TARGET,
    CMP_LINKS_CLICKED_TARGET = @PA_CMP_LINKS_CLICKED_TARGET,
    CMP_LZ_CLICKED_TARGET = @PA_CMP_LZ_CLICKED_TARGET,
    CMP_SURVEYS_COMPLETED_TARGET = @PA_CMP_SURVEYS_COMPLETED_TARGET,
    CMP_GLOBAL_UNSUBSCRIBES_TARGET = @PA_CMP_GLOBAL_UNSUBSCRIBES_TARGET,
    CMP_LIST_UNSUBSCRIBES_TARGET = @PA_CMP_LIST_UNSUBSCRIBES_TARGET,
    CMP_DOCS_DOWNLOADS_TARGET = @PA_CMP_DOCS_DOWNLOADS_TARGET,
    CMP_BOUNCE_BACKS_TARGET = @PA_CMP_BOUNCE_BACKS_TARGET,
    CMP_QCODE = @PA_CMP_QCODE,
    CMP_CURRENT = @PA_CMP_CURRENT
  where CMP_ID = @PA_CMP_ID;
end
go
