//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consensus.Web.BackOffice.membership {
    
    
    public partial class MembershipProductPage {
        
        /// <summary>
        /// ProductDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.membership.controls.MembershipProductDetails ProductDetails;
        
        /// <summary>
        /// PackDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.membership.controls.MembershipPackDetails PackDetails;
        
        /// <summary>
        /// OnlineDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.learning.controls.ProductOnlineDetails OnlineDetails;
        
        /// <summary>
        /// BottomTabControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.Controls.TabControl BottomTabControl;
        
        /// <summary>
        /// PricesList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.learning.ProductPriceList PricesList;
        
        /// <summary>
        /// GradesList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Consensus.Web.BackOffice.membership.controls.MembershipProductGradesList GradesList;
    }
}
