if not exists (select object_id from sys.objects where type = 'P' and name = 'spConsensusMembershipMemberLocationModify')
  exec ('create procedure dbo.spConsensusMembershipMemberLocationModify as select 1 as temp')
go
alter procedure dbo.spConsensusMembershipMemberLocationModify(@PA_MEL_ID varchar(11) = null output, @PA_MEL_MEM_ID varchar(11) = null output, @PA_MEL_MEP_ID varchar(11) = null output, @PA_MEL_START datetime = null output, @PA_MEL_END datetime = null output, @PA_MEL_STATUS integer = null output, @PA_MEL_TYPE integer = null output, @PA_MEL_FEE decimal(19, 4) = null output, @PA_MEL_FEE_BC decimal(19, 4) = null output, @PA_MEL_FEE_BC2 decimal(19, 4) = null output, @PA_MEL_CURRENCY varchar(3) = null output, @PA_MEL_ORG_ID varchar(11) = null output, @PA_MEL_PROLE_ID varchar(11) = null output, @PA_MEL_MAIL_ADD_ID varchar(11) = null output, @PA_MEL_MAIL_INV_ID varchar(11) = null output, @PA_MEL_MAIL_TO_HOME tinyint = null output, @PA_MEL_RENEW_LOC tinyint = null output, @PA_MEL_PRINCIPAL tinyint = null output, @PA_MEL_OVERSEAS tinyint = null output, @PA_MEL_VATCD varchar(25) = null output, @PA_MEL_REF varchar(11) = null output, @PA_MEL_VAT_RATE decimal(19, 4) = null output, @PA_MEL_VAT_AMT decimal(19, 4) = null output, @PA_MEL_VAT_AMT_BC decimal(19, 4) = null output, @PA_MEL_VAT_AMT_BC2 decimal(19, 4) = null output, @PA_MEL_INVLN_ID varchar(11) = null output, @PA_MEL_NO_COPIES integer = null output, @PA_MEL_INVOICED tinyint = null output, @PA_MEL_USERNAME varchar(25) = null output, @PA_MEL_PASSWORD varchar(25) = null output, @PA_MEL_SY_TYPE tinyint = null output, @PA_MEL_PROD_ID varchar(11) = null output, @PA_MEL_CURRENT tinyint = null output, @PA_MEL_GROSS_FEE decimal(19, 4) = null output, @PA_MEL_GROSS_FEE_BC decimal(19, 4) = null output, @PA_MEL_GROSS_FEE_BC2 decimal(19, 4) = null output, @PA_MEL_DISC_REASON varchar(500) = null output, @PA_MEL_PHONE_OVERRIDE varchar(25) = null output, @PA_MEL_FAX_OVERRIDE varchar(25) = null output, @PA_MEL_PHONE_STD_OVERRIDE varchar(10) = null output, @PA_MEL_FAX_STD_OVERRIDE varchar(10) = null output, @PA_MEL_EMAIL_OVERRIDE varchar(240) = null output, @PA_MEL_URL varchar(240) = null output, @PA_MEL_FEE_NOT_PRO_RATA decimal(19, 4) = null output, @PA_MEL_WEB_ENABLED tinyint = null output, @PA_MEL_FEE_EXEMPT tinyint = null output, @PA_MEL_CURRENT_DATE datetime = null output, @PA_MEL_CANCEL_DATE datetime = null output, @PA_MEL_PL_ID varchar(11) = null output, @PA_MEL_DISC_ID integer = null output, @PA_MEL_DISCOUNT decimal(19, 4) = null output, @PA_MEL_DISCOUNT_BC decimal(19, 4) = null output, @PA_MEL_DISCOUNT_BC2 decimal(19, 4) = null output, @PA_MEL_DISC_APPLIED_DATE datetime = null output, @PA_MEL_FEE_CALCULATED tinyint = null output, @PA_MEL_LIST_PRICE decimal(19, 4) = null output, @PA_MEL_LIST_PRICE_BC decimal(19, 4) = null output, @PA_MEL_LIST_PRICE_BC2 decimal(19, 4) = null output, @PA_MEL_DESPATCH_DATE datetime = null output, @PA_MEL_PO_NUMBER varchar(25) = null output, @PA_MEL_QTY integer = null output, @PA_MEL_DO_NOT_RENEW tinyint = null output, @PA_MEL_CANCEL_REASON varchar(40) = null output, @PA_MEL_UNT_PRICE decimal(19, 4) = null output, @PA_MEL_UNT_PRICE_BC decimal(19, 4) = null output, @PA_MEL_UNT_PRICE_BC2 decimal(19, 4) = null output, @PA_MEL_DISC_RENEWAL datetime = null output, @PA_MEL_PRICE_MODIFIED tinyint = null output, @PA_MEL_DISC_PERCENT decimal(19, 2) = null output, @PA_MEL_REV_CODE varchar(40) = null output, @PA_MEL_COST_CODE varchar(40) = null output, @_AUDIT_USER_ID varchar(3) = null) as 
begin
  update dbo.Member_location set
    MEL_MOD_DATE = getDate(),
    MEL_MOD_BY = @_AUDIT_USER_ID,
    MEL_MEM_ID = @PA_MEL_MEM_ID,
    MEL_MEP_ID = @PA_MEL_MEP_ID,
    MEL_START = @PA_MEL_START,
    MEL_END = @PA_MEL_END,
    MEL_STATUS = @PA_MEL_STATUS,
    MEL_TYPE = @PA_MEL_TYPE,
    MEL_FEE = @PA_MEL_FEE,
    MEL_FEE_BC = @PA_MEL_FEE_BC,
    MEL_FEE_BC2 = @PA_MEL_FEE_BC2,
    MEL_CURRENCY = @PA_MEL_CURRENCY,
    MEL_ORG_ID = @PA_MEL_ORG_ID,
    MEL_PROLE_ID = @PA_MEL_PROLE_ID,
    MEL_MAIL_ADD_ID = @PA_MEL_MAIL_ADD_ID,
    MEL_MAIL_INV_ID = @PA_MEL_MAIL_INV_ID,
    MEL_MAIL_TO_HOME = @PA_MEL_MAIL_TO_HOME,
    MEL_RENEW_LOC = @PA_MEL_RENEW_LOC,
    MEL_PRINCIPAL = @PA_MEL_PRINCIPAL,
    MEL_OVERSEAS = @PA_MEL_OVERSEAS,
    MEL_VATCD = @PA_MEL_VATCD,
    MEL_REF = @PA_MEL_REF,
    MEL_VAT_RATE = @PA_MEL_VAT_RATE,
    MEL_VAT_AMT = @PA_MEL_VAT_AMT,
    MEL_VAT_AMT_BC = @PA_MEL_VAT_AMT_BC,
    MEL_VAT_AMT_BC2 = @PA_MEL_VAT_AMT_BC2,
    MEL_INVLN_ID = @PA_MEL_INVLN_ID,
    MEL_NO_COPIES = @PA_MEL_NO_COPIES,
    MEL_INVOICED = @PA_MEL_INVOICED,
    MEL_USERNAME = @PA_MEL_USERNAME,
    MEL_PASSWORD = @PA_MEL_PASSWORD,
    MEL_SY_TYPE = @PA_MEL_SY_TYPE,
    MEL_PROD_ID = @PA_MEL_PROD_ID,
    MEL_CURRENT = @PA_MEL_CURRENT,
    MEL_GROSS_FEE = @PA_MEL_GROSS_FEE,
    MEL_GROSS_FEE_BC = @PA_MEL_GROSS_FEE_BC,
    MEL_GROSS_FEE_BC2 = @PA_MEL_GROSS_FEE_BC2,
    MEL_DISC_REASON = @PA_MEL_DISC_REASON,
    MEL_PHONE_OVERRIDE = @PA_MEL_PHONE_OVERRIDE,
    MEL_FAX_OVERRIDE = @PA_MEL_FAX_OVERRIDE,
    MEL_PHONE_STD_OVERRIDE = @PA_MEL_PHONE_STD_OVERRIDE,
    MEL_FAX_STD_OVERRIDE = @PA_MEL_FAX_STD_OVERRIDE,
    MEL_EMAIL_OVERRIDE = @PA_MEL_EMAIL_OVERRIDE,
    MEL_URL = @PA_MEL_URL,
    MEL_FEE_NOT_PRO_RATA = @PA_MEL_FEE_NOT_PRO_RATA,
    MEL_WEB_ENABLED = @PA_MEL_WEB_ENABLED,
    MEL_FEE_EXEMPT = @PA_MEL_FEE_EXEMPT,
    MEL_CURRENT_DATE = @PA_MEL_CURRENT_DATE,
    MEL_CANCEL_DATE = @PA_MEL_CANCEL_DATE,
    MEL_PL_ID = @PA_MEL_PL_ID,
    MEL_DISC_ID = @PA_MEL_DISC_ID,
    MEL_DISCOUNT = @PA_MEL_DISCOUNT,
    MEL_DISCOUNT_BC = @PA_MEL_DISCOUNT_BC,
    MEL_DISCOUNT_BC2 = @PA_MEL_DISCOUNT_BC2,
    MEL_DISC_APPLIED_DATE = @PA_MEL_DISC_APPLIED_DATE,
    MEL_FEE_CALCULATED = @PA_MEL_FEE_CALCULATED,
    MEL_LIST_PRICE = @PA_MEL_LIST_PRICE,
    MEL_LIST_PRICE_BC = @PA_MEL_LIST_PRICE_BC,
    MEL_LIST_PRICE_BC2 = @PA_MEL_LIST_PRICE_BC2,
    MEL_DESPATCH_DATE = @PA_MEL_DESPATCH_DATE,
    MEL_PO_NUMBER = @PA_MEL_PO_NUMBER,
    MEL_QTY = @PA_MEL_QTY,
    MEL_DO_NOT_RENEW = @PA_MEL_DO_NOT_RENEW,
    MEL_CANCEL_REASON = @PA_MEL_CANCEL_REASON,
    MEL_UNT_PRICE = @PA_MEL_UNT_PRICE,
    MEL_UNT_PRICE_BC = @PA_MEL_UNT_PRICE_BC,
    MEL_UNT_PRICE_BC2 = @PA_MEL_UNT_PRICE_BC2,
    MEL_DISC_RENEWAL = @PA_MEL_DISC_RENEWAL,
    MEL_PRICE_MODIFIED = @PA_MEL_PRICE_MODIFIED,
    MEL_DISC_PERCENT = @PA_MEL_DISC_PERCENT,
    MEL_REV_CODE = @PA_MEL_REV_CODE,
    MEL_COST_CODE = @PA_MEL_COST_CODE
  where MEL_ID = @PA_MEL_ID;
end
go
